const MINCHO_FONT_FAMILY =
  '"Yu Mincho", "Hiragino Mincho ProN", "Hiragino Mincho Pro", "Noto Serif CJK JP", "Noto Serif JP", serif'

const GOTHIC_FONT_FAMILY =
  '"Yu Gothic", "Hiragino Sans", "Hiragino Kaku Gothic ProN", "Noto Sans CJK JP", "Noto Sans JP", sans-serif'

const CHROME_FONT_FAMILY =
  '-apple-system, "Hiragino Kaku Gothic ProN", "Yu Gothic", sans-serif'

/**
 * Web Book reader CSS（固定文字列のみ）。
 * - screen pagination は root geometry variables を読み、print は参照しない。
 * - reader chrome / Settings popover / Outline drawer / backdrop はすべて overlay で、
 *   pagination viewport の layout height / width を予約しない。
 * - WB-R5 page transition は screen 専用の演出（viewport opacity / 小さな
 *   visual transform、mask / overlay の物理 x sweep）で、CSS Columns の計測
 *   対象・canonical transform を変えない。reduced motion / print では無効。
 */
export function buildWebBookReaderCss(): string {

  return [
    '/* Web Book reader CSS — reader furniture / overlay chrome / screen columns; print is neutral. */',
    ':root {',
    '  /* 旧 16px 基準の 110% を、新しい reader の 100% 基準にする。 */',
    '  --wb-base-font-size: 17.6px;',
    '  --wb-font-scale: 1;',
    `  --wb-font-family-mincho: ${MINCHO_FONT_FAMILY};`,
    `  --wb-font-family-gothic: ${GOTHIC_FONT_FAMILY};`,
    '  --wb-font-family: var(--wb-font-family-mincho);',
    '  --wb-bg: #ffffff;',
    '  --wb-fg: #1a1a1a;',
    '  --wb-heading: #1a1a1a;',
    '  --wb-muted: #555555;',
    '  --wb-canvas: #f2f0ea;',
    '  --wb-chrome-bg: #fafafa;',
    '  --wb-chrome-border: #dddddd;',
    '  --wb-chrome-fg: #1a1a1a;',
    '  --wb-outline-bg: #ffffff;',
    '  --wb-outline-shadow: rgba(0, 0, 0, 0.28);',
    '  --wb-accent: #2a5db0;',
    '  --wb-frame-width: 0px;',
    '  --wb-frame-height: 0px;',
    '  --wb-page-pitch: 0px;',
    '  --wb-column-width: 0px;',
    '  --wb-column-gap: 0px;',
    '  --wb-inline-padding: 0px;',
    '  --wb-page-inset-top: 32px;',
    '  --wb-page-inset-bottom: 16px;',
    '  --wb-page-inset-inline: 16px;',
    '  --wb-effective-page-inset-top: 48px;',
    '  --wb-effective-page-inset-bottom: 32px;',
    '  --wb-effective-page-inset-inline: 16px;',
    '  --wb-page-offset: 0px;',
    '}',
    '',
    '/* Classic = WB-R3B までの固定 Author / Original palette。 */',
    'body.nyoze-web-book-root[data-wb-theme="classic"],',
    'body.nyoze-web-book-root:not([data-wb-theme]) {',
    '  --wb-bg: #fffef8;',
    '  --wb-fg: #1a1a1a;',
    '  --wb-heading: #1a1a1a;',
    '  --wb-muted: #5a5a5a;',
    '  --wb-canvas: #efe9dc;',
    '  --wb-chrome-bg: #f7f4ec;',
    '  --wb-chrome-border: #d8d0c0;',
    '  --wb-chrome-fg: #1a1a1a;',
    '  --wb-outline-bg: #fffef8;',
    '  --wb-accent: #6b4f2a;',
    '}',
    'body.nyoze-web-book-root[data-wb-theme="light"] {',
    '  --wb-bg: #ffffff;',
    '  --wb-fg: #1a1a1a;',
    '  --wb-heading: #1a1a1a;',
    '  --wb-muted: #555555;',
    '  --wb-canvas: #ececee;',
    '  --wb-chrome-bg: #fafafa;',
    '  --wb-chrome-border: #dddddd;',
    '  --wb-chrome-fg: #1a1a1a;',
    '  --wb-outline-bg: #ffffff;',
    '  --wb-accent: #2a5db0;',
    '}',
    'body.nyoze-web-book-root[data-wb-theme="dark"] {',
    '  --wb-bg: #1b1b1f;',
    '  --wb-fg: #ececf1;',
    '  --wb-heading: #ececf1;',
    '  --wb-muted: #b0b0bc;',
    '  --wb-canvas: #121216;',
    '  --wb-chrome-bg: #25252c;',
    '  --wb-chrome-border: #3a3a44;',
    '  --wb-chrome-fg: #ececf1;',
    '  --wb-outline-bg: #222228;',
    '  --wb-outline-shadow: rgba(0, 0, 0, 0.55);',
    '  --wb-accent: #8ab4ff;',
    '}',
    'body.nyoze-web-book-root[data-wb-theme="paper"] {',
    '  --wb-bg: #f3e7d3;',
    '  --wb-fg: #2c2418;',
    '  --wb-heading: #2c2418;',
    '  --wb-muted: #6a5a44;',
    '  --wb-canvas: #e3d4b8;',
    '  --wb-chrome-bg: #ecdfc8;',
    '  --wb-chrome-border: #cbb99a;',
    '  --wb-chrome-fg: #2c2418;',
    '  --wb-outline-bg: #f7ecda;',
    '  --wb-accent: #8a5a2b;',
    '}',
    '',
    'html, body { margin: 0; }',
    'body.nyoze-web-book-root {',
    '  box-sizing: border-box;',
    '  writing-mode: horizontal-tb;',
    '  background: var(--wb-bg);',
    '  color: var(--wb-fg);',
    '  font-family: var(--wb-font-family);',
    '  font-size: calc(var(--wb-base-font-size) * var(--wb-font-scale));',
    '  line-height: 1.9;',
    '}',
    'body.nyoze-web-book-root[data-wb-writing-mode="vertical-rl"] .nyoze-web-book-viewport,',
    'body.nyoze-web-book-root[data-wb-writing-mode="vertical-rl"] .nyoze-web-book-flow {',
    '  writing-mode: vertical-rl;',
    '}',
    'body.nyoze-web-book-root[data-wb-writing-mode="horizontal-tb"] .nyoze-web-book-viewport,',
    'body.nyoze-web-book-root[data-wb-writing-mode="horizontal-tb"] .nyoze-web-book-flow {',
    '  writing-mode: horizontal-tb;',
    '}',
    '',
    '/* ============================================================',
    '   Compact overlay chrome — fixed / no layout reservation.',
    '   Auto-hide is opacity + visibility + pointer-events only, so a',
    '   hidden chrome never blocks the reading surface underneath.',
    '   ============================================================ */',
    '.nyoze-web-book-chrome {',
    '  position: fixed;',
    '  top: 10px;',
    '  left: 50%;',
    '  transform: translateX(-50%);',
    '  z-index: 30;',
    '  display: inline-flex;',
    '  align-items: center;',
    '  gap: 2px;',
    '  /* fixed + left:50% の shrink-to-fit は viewport 半分に縮むため max-content を明示する。 */',
    '  width: max-content;',
    '  max-width: calc(100vw - 16px);',
    '  box-sizing: border-box;',
    '  padding: 3px 6px;',
    '  writing-mode: horizontal-tb;',
    '  direction: ltr;',
    `  font-family: ${CHROME_FONT_FAMILY};`,
    '  font-size: 12.5px;',
    '  color: var(--wb-chrome-fg);',
    '  background: var(--wb-chrome-bg);',
    '  background: color-mix(in srgb, var(--wb-chrome-bg) 84%, transparent);',
    '  -webkit-backdrop-filter: blur(10px);',
    '  backdrop-filter: blur(10px);',
    '  border: 1px solid color-mix(in srgb, var(--wb-chrome-border) 80%, transparent);',
    '  border-radius: 999px;',
    '  box-shadow: 0 2px 10px color-mix(in srgb, var(--wb-outline-shadow) 30%, transparent);',
    '  transition: opacity 0.25s ease, visibility 0s linear 0s;',
    '}',
    '.nyoze-web-book-chrome__nav {',
    '  display: inline-flex;',
    '  align-items: center;',
    '  gap: 2px;',
    '}',
    '.nyoze-web-book-chrome__status {',
    '  min-width: 3.2em;',
    '  text-align: center;',
    '  font-variant-numeric: tabular-nums;',
    '  color: var(--wb-muted);',
    '}',
    '.nyoze-web-book-chrome__divider {',
    '  width: 1px;',
    '  align-self: stretch;',
    '  margin: 5px 5px;',
    '  background: color-mix(in srgb, var(--wb-chrome-border) 90%, transparent);',
    '}',
    '.nyoze-web-book-chrome button {',
    '  font: inherit;',
    '  cursor: pointer;',
    '  border: none;',
    '  background: transparent;',
    '  color: var(--wb-chrome-fg);',
    '  border-radius: 999px;',
    '  padding: 0.32rem 0.72rem;',
    '  line-height: 1.3;',
    '  white-space: nowrap;',
    '  transition: background-color 0.15s ease;',
    '}',
    '.nyoze-web-book-chrome button:hover:not(:disabled) {',
    '  background: color-mix(in srgb, var(--wb-fg) 8%, transparent);',
    '}',
    '.nyoze-web-book-chrome button:active:not(:disabled) {',
    '  background: color-mix(in srgb, var(--wb-fg) 14%, transparent);',
    '}',
    '.nyoze-web-book-chrome button:focus-visible {',
    '  outline: 2px solid var(--wb-accent);',
    '  outline-offset: 1px;',
    '}',
    '.nyoze-web-book-chrome button[aria-expanded="true"] {',
    '  background: color-mix(in srgb, var(--wb-accent) 16%, transparent);',
    '}',
    '.nyoze-web-book-chrome button:disabled {',
    '  opacity: 0.38;',
    '  cursor: default;',
    '}',
    'body.nyoze-web-book-chrome-hidden .nyoze-web-book-chrome {',
    '  opacity: 0;',
    '  visibility: hidden;',
    '  pointer-events: none;',
    '  transition: opacity 0.25s ease, visibility 0s linear 0.25s;',
    '}',
    '',
    '/* ============================================================',
    '   Reader Settings popover — session-only controls.',
    '   Fixed overlay: opening never reflows the pagination viewport.',
    '   ============================================================ */',
    '.nyoze-web-book-settings {',
    '  position: fixed;',
    '  top: 54px;',
    '  left: 50%;',
    '  transform: translateX(-50%);',
    '  z-index: 45;',
    '  box-sizing: border-box;',
    '  width: min(19.5rem, calc(100vw - 24px));',
    '  max-height: calc(100dvh - 66px);',
    '  overflow-y: auto;',
    '  overscroll-behavior: contain;',
    '  padding: 0.55rem 0.8rem 0.7rem;',
    '  writing-mode: horizontal-tb;',
    '  direction: ltr;',
    `  font-family: ${CHROME_FONT_FAMILY};`,
    '  font-size: 12.5px;',
    '  color: var(--wb-chrome-fg);',
    '  background: var(--wb-chrome-bg);',
    '  border: 1px solid var(--wb-chrome-border);',
    '  border-radius: 12px;',
    '  box-shadow: 0 10px 34px color-mix(in srgb, var(--wb-outline-shadow) 70%, transparent);',
    '  animation: wb-pop-in 0.14s ease-out;',
    '}',
    '.nyoze-web-book-settings[hidden] { display: none !important; }',
    '.nyoze-web-book-settings:focus { outline: none; }',
    '.nyoze-web-book-settings__section {',
    '  min-width: 0;',
    '  margin: 0;',
    '  padding: 0.2rem 0 0.35rem;',
    '  border: 0;',
    '}',
    '.nyoze-web-book-settings__section + .nyoze-web-book-settings__section {',
    '  border-top: 1px solid color-mix(in srgb, var(--wb-chrome-border) 55%, transparent);',
    '}',
    '.nyoze-web-book-settings__section legend {',
    '  padding: 0;',
    '  color: var(--wb-muted);',
    '  font-size: 0.78rem;',
    '  font-weight: 600;',
    '}',
    '.nyoze-web-book-settings__hint {',
    '  display: block;',
    '  margin: 0.05rem 0 0.2rem;',
    '  color: var(--wb-muted);',
    '  font-size: 0.72rem;',
    '}',
    '.nyoze-web-book-settings__row {',
    '  display: flex;',
    '  align-items: center;',
    '  justify-content: space-between;',
    '  gap: 0.75rem;',
    '  min-height: 2.1rem;',
    '  padding: 0.15rem 0;',
    '}',
    '.nyoze-web-book-settings__label {',
    '  color: var(--wb-muted);',
    '  flex: 0 0 auto;',
    '}',
    '.nyoze-web-book-settings__group {',
    '  display: inline-flex;',
    '  align-items: center;',
    '  gap: 0.2rem;',
    '}',
    '.nyoze-web-book-settings__value {',
    '  min-width: 3.2em;',
    '  text-align: center;',
    '  font-variant-numeric: tabular-nums;',
    '}',
    '.nyoze-web-book-settings__segmented {',
    '  display: inline-flex;',
    '  border: 1px solid var(--wb-chrome-border);',
    '  border-radius: 8px;',
    '  overflow: hidden;',
    '}',
    '.nyoze-web-book-settings__segmented button {',
    '  border: none;',
    '  border-radius: 0;',
    '}',
    '.nyoze-web-book-settings__segmented button + button {',
    '  border-left: 1px solid color-mix(in srgb, var(--wb-chrome-border) 70%, transparent);',
    '}',
    '.nyoze-web-book-settings button {',
    '  font: inherit;',
    '  cursor: pointer;',
    '  border: 1px solid var(--wb-chrome-border);',
    '  background: transparent;',
    '  color: var(--wb-chrome-fg);',
    '  border-radius: 7px;',
    '  padding: 0.3rem 0.65rem;',
    '  line-height: 1.3;',
    '  transition: background-color 0.15s ease;',
    '}',
    '.nyoze-web-book-settings button:hover:not(:disabled) {',
    '  background: color-mix(in srgb, var(--wb-fg) 7%, transparent);',
    '}',
    '.nyoze-web-book-settings button:active:not(:disabled) {',
    '  background: color-mix(in srgb, var(--wb-fg) 13%, transparent);',
    '}',
    '.nyoze-web-book-settings button:focus-visible {',
    '  outline: 2px solid var(--wb-accent);',
    '  outline-offset: 1px;',
    '}',
    '.nyoze-web-book-settings button:disabled {',
    '  opacity: 0.38;',
    '  cursor: default;',
    '}',
    '.nyoze-web-book-settings button[aria-pressed="true"] {',
    '  background: color-mix(in srgb, var(--wb-accent) 15%, transparent);',
    '  color: var(--wb-chrome-fg);',
    '  box-shadow: inset 0 0 0 1px color-mix(in srgb, var(--wb-accent) 55%, transparent);',
    '}',
    '.nyoze-web-book-settings select {',
    '  font: inherit;',
    '  color: var(--wb-chrome-fg);',
    '  background: var(--wb-bg);',
    '  border: 1px solid var(--wb-chrome-border);',
    '  border-radius: 7px;',
    '  padding: 0.28rem 0.4rem;',
    '  max-width: 11rem;',
    '}',
    '.nyoze-web-book-settings select:focus-visible {',
    '  outline: 2px solid var(--wb-accent);',
    '  outline-offset: 1px;',
    '}',
    '.nyoze-web-book-settings input[type="range"] {',
    '  width: 7rem;',
    '  accent-color: var(--wb-accent);',
    '}',
    '.nyoze-web-book-settings input[type="range"]:disabled {',
    '  opacity: 0.38;',
    '}',
    '.nyoze-web-book-settings input[type="range"]:focus-visible {',
    '  outline: 2px solid var(--wb-accent);',
    '  outline-offset: 1px;',
    '}',
    '.nyoze-web-book-settings__footer {',
    '  display: flex;',
    '  justify-content: flex-end;',
    '  padding-top: 0.5rem;',
    '  margin-top: 0.2rem;',
    '  border-top: 1px solid color-mix(in srgb, var(--wb-chrome-border) 55%, transparent);',
    '}',
    '',
    '/* Shared backdrop for the Outline drawer. */',
    '.nyoze-web-book-backdrop {',
    '  position: fixed;',
    '  inset: 0;',
    '  z-index: 38;',
    '  background: color-mix(in srgb, #000000 30%, transparent);',
    '  animation: wb-fade-in 0.16s ease-out;',
    '}',
    '.nyoze-web-book-backdrop[hidden] { display: none !important; }',
    '',
    '@keyframes wb-pop-in {',
    '  from { opacity: 0; transform: translateX(-50%) translateY(-4px); }',
    '  to { opacity: 1; transform: translateX(-50%) translateY(0); }',
    '}',
    '@keyframes wb-fade-in {',
    '  from { opacity: 0; }',
    '  to { opacity: 1; }',
    '}',
    '@keyframes wb-drawer-in {',
    '  from { opacity: 0.5; transform: translateX(16px); }',
    '  to { opacity: 1; transform: translateX(0); }',
    '}',
    '@media (prefers-reduced-motion: reduce) {',
    '  body.nyoze-web-book-root,',
    '  .nyoze-web-book-chrome,',
    '  .nyoze-web-book-chrome button,',
    '  .nyoze-web-book-settings,',
    '  .nyoze-web-book-settings button,',
    '  .nyoze-web-book-backdrop,',
    '  .nyoze-web-book-outline {',
    '    transition: none !important;',
    '    animation: none !important;',
    '  }',
    '  /* WB-R5: reduced motion では方式にかかわらず実効遷移 none（script 側の',
    '     matchMedia gate が正、この宣言は CSS 側の安全網）。 */',
    '  .nyoze-web-book-viewport.is-wb-transition-fade-out,',
    '  .nyoze-web-book-viewport.is-wb-transition-fade-in,',
    '  .nyoze-web-book-viewport.is-wb-transition-zoom,',
    '  .nyoze-web-book-transition-mask.is-wb-transition-slide,',
    '  .nyoze-web-book-transition-overlay.is-wb-transition-slide {',
    '    animation: none !important;',
    '  }',
    '}',
    '',
    '/* ============================================================',
    '   Outline — physical right drawer over a backdrop.',
    '   Overlay only: never shrinks the pagination viewport.',
    '   ============================================================ */',
    '.nyoze-web-book-outline {',
    '  writing-mode: horizontal-tb;',
    '  direction: ltr;',
    '  position: fixed;',
    '  top: 0;',
    '  right: 0;',
    '  bottom: 0;',
    '  left: auto;',
    '  width: min(19rem, 86vw);',
    '  z-index: 40;',
    '  box-sizing: border-box;',
    '  overflow: auto;',
    '  overscroll-behavior: contain;',
    '  padding: 0.85rem 0.85rem 1.25rem;',
    '  background: var(--wb-outline-bg);',
    '  background: color-mix(in srgb, var(--wb-outline-bg) 94%, transparent);',
    '  -webkit-backdrop-filter: blur(10px);',
    '  backdrop-filter: blur(10px);',
    '  color: var(--wb-fg);',
    '  border-left: 1px solid var(--wb-chrome-border);',
    '  box-shadow: -6px 0 26px var(--wb-outline-shadow);',
    `  font-family: ${CHROME_FONT_FAMILY};`,
    '  font-size: 13.5px;',
    '  line-height: 1.45;',
    '  animation: wb-drawer-in 0.18s ease-out;',
    '}',
    '.nyoze-web-book-outline[hidden] {',
    '  display: none !important;',
    '}',
    '.nyoze-web-book-outline:focus { outline: none; }',
    '.nyoze-web-book-outline__title {',
    '  margin: 0 0 0.65rem;',
    '  padding: 0 0.45rem;',
    '  font-size: 0.9rem;',
    '  font-weight: 600;',
    '  color: var(--wb-muted);',
    '}',
    '.nyoze-web-book-outline__list {',
    '  list-style: none;',
    '  margin: 0;',
    '  padding: 0;',
    '}',
    '.nyoze-web-book-outline__chapter {',
    '  margin: 0.75rem 0 0.25rem;',
    '  padding: 0;',
    '  font-weight: 600;',
    '  color: var(--wb-muted);',
    '}',
    '.nyoze-web-book-outline__chapter button {',
    '  display: block;',
    '  width: 100%;',
    '  text-align: start;',
    '  font: inherit;',
    '  font-weight: 600;',
    '  color: inherit;',
    '  background: transparent;',
    '  border: none;',
    '  border-radius: 6px;',
    '  padding: 0.4rem 0.45rem;',
    '  cursor: pointer;',
    '  transition: background-color 0.15s ease;',
    '}',
    '.nyoze-web-book-outline__chapter button:hover,',
    '.nyoze-web-book-outline__chapter button:focus-visible {',
    '  background: color-mix(in srgb, var(--wb-accent) 14%, transparent);',
    '  outline: none;',
    '}',
    '.nyoze-web-book-outline__chapter button:active {',
    '  background: color-mix(in srgb, var(--wb-accent) 22%, transparent);',
    '}',
    '.nyoze-web-book-outline__item {',
    '  margin: 0;',
    '}',
    '.nyoze-web-book-outline__item button {',
    '  display: block;',
    '  width: 100%;',
    '  text-align: start;',
    '  font: inherit;',
    '  color: inherit;',
    '  background: transparent;',
    '  border: none;',
    '  border-radius: 6px;',
    '  padding: 0.4rem 0.45rem;',
    '  cursor: pointer;',
    '  transition: background-color 0.15s ease;',
    '}',
    '.nyoze-web-book-outline__item button:hover,',
    '.nyoze-web-book-outline__item button:focus-visible {',
    '  background: color-mix(in srgb, var(--wb-accent) 14%, transparent);',
    '  outline: none;',
    '}',
    '.nyoze-web-book-outline__item button:active {',
    '  background: color-mix(in srgb, var(--wb-accent) 22%, transparent);',
    '}',
    '.nyoze-web-book-outline__level-1 { padding-inline-start: 0; }',
    '.nyoze-web-book-outline__level-2 { padding-inline-start: 0.75rem; }',
    '.nyoze-web-book-outline__level-3 { padding-inline-start: 1.5rem; }',
    '.nyoze-web-book-outline__level-4 { padding-inline-start: 2.25rem; }',
    '.nyoze-web-book-outline__level-5 { padding-inline-start: 3rem; }',
    '.nyoze-web-book-outline__level-6 { padding-inline-start: 3.75rem; }',
    '',
    '.nyoze-web-book-flow {',
    '  direction: ltr;',
    '  box-sizing: border-box;',
    '  font-family: var(--wb-font-family);',
    '  color: var(--wb-fg);',
    '  line-break: strict;',
    '  word-break: normal;',
    '  overflow-wrap: break-word;',
    '  hanging-punctuation: first allow-end;',
    '  text-wrap: pretty;',
    '}',
    '.nyoze-web-book-flow p { margin: 0; }',
    '/* Chromium inline 境界折り返し補正（HTML export / Editor / Page Viewer と同意図）。',
    '   段落末が全角閉じ括弧で、手前に ruby / strong / link / TCY 等の inline 境界があるとき、',
    '   Chromium は行末で境界まで折り返し位置を巻き戻すことがある',
    '   （docs/vertical-inline-boundary-line-break-investigation.md）。',
    '   CSS generated content の U+200B のみで回避し、semantic HTML / textContent /',
    '   Markdown / reader script には混入させない。空 alternative text で SR 非露出。',
    '   対象は通常 paragraph のみ（見出し / TOC / chrome / code は対象外）。',
    '   静的 HTML のため writing-mode を問わず適用し、screen / print で共有する。 */',
    '.nyoze-web-book-flow p::after {',
    '  content: "\\200B" / "";',
    '}',
    '/* 空段落（<br> のみ）は閉じ括弧問題が起きないため補正対象外。 */',
    '.nyoze-web-book-flow p:has(> br:only-child)::after {',
    '  content: none;',
    '}',
    '/* WB-R8: 本文見出し appearance（Display Settings snapshot）。',
    '   文書タイトル / 章タイトル / TOC 見出しは対象外。色は既存 --wb-heading。 */',
    '.nyoze-web-book-flow h1:not(.nyoze-document-title):not(.nyoze-chapter-title):not(.nyoze-toc-title),',
    '.nyoze-web-book-flow h2:not(.nyoze-document-title):not(.nyoze-chapter-title):not(.nyoze-toc-title),',
    '.nyoze-web-book-flow h3:not(.nyoze-document-title):not(.nyoze-chapter-title):not(.nyoze-toc-title),',
    '.nyoze-web-book-flow h4:not(.nyoze-document-title):not(.nyoze-chapter-title):not(.nyoze-toc-title),',
    '.nyoze-web-book-flow h5:not(.nyoze-document-title):not(.nyoze-chapter-title):not(.nyoze-toc-title),',
    '.nyoze-web-book-flow h6:not(.nyoze-document-title):not(.nyoze-chapter-title):not(.nyoze-toc-title) {',
    '  margin: 1.25em 0 0;',
    '  margin-block-end: var(--wb-heading-margin-after, 0.45em);',
    '  line-height: 1.4;',
    '  font-family: var(--wb-font-family);',
    '  color: var(--wb-heading);',
    '  border-block-end-style: solid;',
    '  border-block-end-width: 0;',
    '  border-block-end-color: color-mix(in srgb, var(--wb-heading) 34%, var(--wb-bg) 66%);',
    '}',
    'body.nyoze-web-book-root[data-wb-writing-mode="horizontal-tb"] .nyoze-web-book-flow h1:not(.nyoze-document-title):not(.nyoze-chapter-title):not(.nyoze-toc-title),',
    'body.nyoze-web-book-root[data-wb-writing-mode="horizontal-tb"] .nyoze-web-book-flow h2:not(.nyoze-document-title):not(.nyoze-chapter-title):not(.nyoze-toc-title),',
    'body.nyoze-web-book-root[data-wb-writing-mode="horizontal-tb"] .nyoze-web-book-flow h3:not(.nyoze-document-title):not(.nyoze-chapter-title):not(.nyoze-toc-title),',
    'body.nyoze-web-book-root[data-wb-writing-mode="horizontal-tb"] .nyoze-web-book-flow h4:not(.nyoze-document-title):not(.nyoze-chapter-title):not(.nyoze-toc-title),',
    'body.nyoze-web-book-root[data-wb-writing-mode="horizontal-tb"] .nyoze-web-book-flow h5:not(.nyoze-document-title):not(.nyoze-chapter-title):not(.nyoze-toc-title),',
    'body.nyoze-web-book-root[data-wb-writing-mode="horizontal-tb"] .nyoze-web-book-flow h6:not(.nyoze-document-title):not(.nyoze-chapter-title):not(.nyoze-toc-title) {',
    '  text-align: var(--wb-heading-align-h, start);',
    '}',
    'body.nyoze-web-book-root[data-wb-writing-mode="vertical-rl"] .nyoze-web-book-flow h1:not(.nyoze-document-title):not(.nyoze-chapter-title):not(.nyoze-toc-title),',
    'body.nyoze-web-book-root[data-wb-writing-mode="vertical-rl"] .nyoze-web-book-flow h2:not(.nyoze-document-title):not(.nyoze-chapter-title):not(.nyoze-toc-title),',
    'body.nyoze-web-book-root[data-wb-writing-mode="vertical-rl"] .nyoze-web-book-flow h3:not(.nyoze-document-title):not(.nyoze-chapter-title):not(.nyoze-toc-title),',
    'body.nyoze-web-book-root[data-wb-writing-mode="vertical-rl"] .nyoze-web-book-flow h4:not(.nyoze-document-title):not(.nyoze-chapter-title):not(.nyoze-toc-title),',
    'body.nyoze-web-book-root[data-wb-writing-mode="vertical-rl"] .nyoze-web-book-flow h5:not(.nyoze-document-title):not(.nyoze-chapter-title):not(.nyoze-toc-title),',
    'body.nyoze-web-book-root[data-wb-writing-mode="vertical-rl"] .nyoze-web-book-flow h6:not(.nyoze-document-title):not(.nyoze-chapter-title):not(.nyoze-toc-title) {',
    '  text-align: var(--wb-heading-align-v, start);',
    '}',
    'body.nyoze-web-book-root[data-wb-heading-font="mincho"] .nyoze-web-book-flow h1:not(.nyoze-document-title):not(.nyoze-chapter-title):not(.nyoze-toc-title),',
    'body.nyoze-web-book-root[data-wb-heading-font="mincho"] .nyoze-web-book-flow h2:not(.nyoze-document-title):not(.nyoze-chapter-title):not(.nyoze-toc-title),',
    'body.nyoze-web-book-root[data-wb-heading-font="mincho"] .nyoze-web-book-flow h3:not(.nyoze-document-title):not(.nyoze-chapter-title):not(.nyoze-toc-title),',
    'body.nyoze-web-book-root[data-wb-heading-font="mincho"] .nyoze-web-book-flow h4:not(.nyoze-document-title):not(.nyoze-chapter-title):not(.nyoze-toc-title),',
    'body.nyoze-web-book-root[data-wb-heading-font="mincho"] .nyoze-web-book-flow h5:not(.nyoze-document-title):not(.nyoze-chapter-title):not(.nyoze-toc-title),',
    'body.nyoze-web-book-root[data-wb-heading-font="mincho"] .nyoze-web-book-flow h6:not(.nyoze-document-title):not(.nyoze-chapter-title):not(.nyoze-toc-title) {',
    '  font-family: var(--wb-font-family-mincho);',
    '}',
    'body.nyoze-web-book-root[data-wb-heading-font="gothic"] .nyoze-web-book-flow h1:not(.nyoze-document-title):not(.nyoze-chapter-title):not(.nyoze-toc-title),',
    'body.nyoze-web-book-root[data-wb-heading-font="gothic"] .nyoze-web-book-flow h2:not(.nyoze-document-title):not(.nyoze-chapter-title):not(.nyoze-toc-title),',
    'body.nyoze-web-book-root[data-wb-heading-font="gothic"] .nyoze-web-book-flow h3:not(.nyoze-document-title):not(.nyoze-chapter-title):not(.nyoze-toc-title),',
    'body.nyoze-web-book-root[data-wb-heading-font="gothic"] .nyoze-web-book-flow h4:not(.nyoze-document-title):not(.nyoze-chapter-title):not(.nyoze-toc-title),',
    'body.nyoze-web-book-root[data-wb-heading-font="gothic"] .nyoze-web-book-flow h5:not(.nyoze-document-title):not(.nyoze-chapter-title):not(.nyoze-toc-title),',
    'body.nyoze-web-book-root[data-wb-heading-font="gothic"] .nyoze-web-book-flow h6:not(.nyoze-document-title):not(.nyoze-chapter-title):not(.nyoze-toc-title) {',
    '  font-family: var(--wb-font-family-gothic);',
    '}',
    'body.nyoze-web-book-root[data-wb-heading-font="same-as-body"] .nyoze-web-book-flow h1:not(.nyoze-document-title):not(.nyoze-chapter-title):not(.nyoze-toc-title),',
    'body.nyoze-web-book-root[data-wb-heading-font="same-as-body"] .nyoze-web-book-flow h2:not(.nyoze-document-title):not(.nyoze-chapter-title):not(.nyoze-toc-title),',
    'body.nyoze-web-book-root[data-wb-heading-font="same-as-body"] .nyoze-web-book-flow h3:not(.nyoze-document-title):not(.nyoze-chapter-title):not(.nyoze-toc-title),',
    'body.nyoze-web-book-root[data-wb-heading-font="same-as-body"] .nyoze-web-book-flow h4:not(.nyoze-document-title):not(.nyoze-chapter-title):not(.nyoze-toc-title),',
    'body.nyoze-web-book-root[data-wb-heading-font="same-as-body"] .nyoze-web-book-flow h5:not(.nyoze-document-title):not(.nyoze-chapter-title):not(.nyoze-toc-title),',
    'body.nyoze-web-book-root[data-wb-heading-font="same-as-body"] .nyoze-web-book-flow h6:not(.nyoze-document-title):not(.nyoze-chapter-title):not(.nyoze-toc-title) {',
    '  font-family: var(--wb-font-family);',
    '}',
    '.nyoze-web-book-flow h1:not(.nyoze-document-title):not(.nyoze-chapter-title):not(.nyoze-toc-title) {',
    '  border-block-end-width: calc(var(--wb-heading-divider-h1, 0) * 1px);',
    '}',
    '.nyoze-web-book-flow h2:not(.nyoze-document-title):not(.nyoze-chapter-title):not(.nyoze-toc-title) {',
    '  border-block-end-width: calc(var(--wb-heading-divider-h2, 0) * 1px);',
    '}',
    '.nyoze-web-book-flow h3:not(.nyoze-document-title):not(.nyoze-chapter-title):not(.nyoze-toc-title) {',
    '  border-block-end-width: calc(var(--wb-heading-divider-h3, 0) * 1px);',
    '}',
    '.nyoze-web-book-flow h4:not(.nyoze-document-title):not(.nyoze-chapter-title):not(.nyoze-toc-title) {',
    '  border-block-end-width: calc(var(--wb-heading-divider-h4, 0) * 1px);',
    '}',
    '.nyoze-web-book-flow h5:not(.nyoze-document-title):not(.nyoze-chapter-title):not(.nyoze-toc-title) {',
    '  border-block-end-width: calc(var(--wb-heading-divider-h5, 0) * 1px);',
    '}',
    '.nyoze-web-book-flow h6:not(.nyoze-document-title):not(.nyoze-chapter-title):not(.nyoze-toc-title) {',
    '  border-block-end-width: calc(var(--wb-heading-divider-h6, 0) * 1px);',
    '}',
    '/* WB-R8: synthetic タイトルは本文見出し appearance の対象外。色だけ theme に合わせる。 */',
    '.nyoze-web-book-flow .nyoze-document-title,',
    '.nyoze-web-book-flow .nyoze-chapter-title {',
    '  margin: 0 0 0.25em;',
    '  line-height: 1.4;',
    '  font-family: inherit;',
    '  color: var(--wb-heading);',
    '  text-align: start;',
    '  border-block-end: none;',
    '}',
    '/* WB-R15: 章ファイル情報タイトルは H1 相当（2em / bold）。本文見出し appearance は非適用。 */',
    '.nyoze-web-book-flow .nyoze-chapter-title {',
    '  margin-block-end: 0.2em;',
    '  font-size: 2em;',
    '  font-weight: bold;',
    '}',
    '/* WB-R15: 章先頭ナビ専用 root。geometry / pageCount を変えない。 */',
    '.nyoze-web-book-flow .nyoze-chapter-root {',
    '  display: block;',
    '  width: 0;',
    '  height: 0;',
    '  margin: 0;',
    '  padding: 0;',
    '  border: 0;',
    '  overflow: hidden;',
    '  visibility: hidden;',
    '  pointer-events: none;',
    '  font-size: 0;',
    '  line-height: 0;',
    '}',
    '/* リンクはブラウザ既定色ではなく theme の accent（Dark で判読できるように）。 */',
    '.nyoze-web-book-flow a {',
    '  color: var(--wb-accent);',
    '  text-underline-offset: 3px;',
    '}',
    '.nyoze-web-book-flow ruby { ruby-position: over; }',
    '.nyoze-web-book-flow rt { font-size: 0.55em; }',
    '.nyoze-web-book-flow code, .nyoze-web-book-flow pre {',
    '  font-family: ui-monospace, SFMono-Regular, Menlo, Consolas, monospace;',
    '  text-align: start;',
    '}',
    '.nyoze-web-book-flow .nyoze-align-center { text-align: center; }',
    '.nyoze-web-book-flow .nyoze-align-end { text-align: end; }',
    '/* WB-R10: :::indent-N — エディタと同じ logical padding-inline-start、step 1.4em。',
    '   既存の inline --nyoze-indent-level を使う。縦書きでは上側、横書きでは左側。 */',
    '.nyoze-web-book-flow .nyoze-indent {',
    '  padding-inline-start: calc(1.4em * var(--nyoze-indent-level, 1));',
    '}',
    '/* WB-R10: 組み込み :::style-*（letter / muted / heading）。theme token で Classic〜Paper',
    '   + Author と print 中立 palette に追従。未知 style 用ルールは追加しない（本文相当）。',
    '   .nyoze-style-heading は本文見出しの WB-R8 snapshot / Reader 見出し書体の対象外。 */',
    '.nyoze-web-book-flow .nyoze-style-letter {',
    '  padding-block: 0.3em;',
    '  padding-inline: 0.6em;',
    '  color: var(--wb-muted);',
    '  line-height: 1.9;',
    '}',
    '.nyoze-web-book-flow .nyoze-style-muted {',
    '  color: var(--wb-muted);',
    '  font-size: 0.92em;',
    '}',
    '.nyoze-web-book-flow .nyoze-style-heading {',
    '  color: var(--wb-heading);',
    '  font-size: 1.15em;',
    '  font-weight: 600;',
    '  letter-spacing: 0.05em;',
    '}',
    '/* WB-R10: task list — native marker を消し、checkbox と先頭段落を同じ line box へ',
    '   （先頭 p を inline 化）。物理 margin の片側合わせではなく logical な inline flow。',
    '   2 段落目以降 / nested list は従来どおり block。text-align: start は下記の',
    '   justify 除外セレクタと共有。 */',
    '.nyoze-web-book-flow li.nyoze-task-item {',
    '  list-style: none;',
    '}',
    '.nyoze-web-book-flow li.nyoze-task-item > input[type="checkbox"] {',
    '  margin-inline-end: 0.35em;',
    '}',
    '.nyoze-web-book-flow li.nyoze-task-item > input[type="checkbox"] + p {',
    '  display: inline;',
    '}',
    '.nyoze-web-book-flow .nyoze-toc,',
    '.nyoze-web-book-flow .nyoze-document-info,',
    '.nyoze-web-book-flow .nyoze-chapter-info,',
    '.nyoze-web-book-flow li.nyoze-task-item { text-align: start; }',
    '/* WB-R7: 著者/訳者行は地付き（logical end）。info 全体の start と flow justify より',
    '   class 2つの specificity で勝つ。 */',
    '.nyoze-web-book-flow .nyoze-document-credit,',
    '.nyoze-web-book-flow .nyoze-chapter-credit { text-align: end; }',
    '/* WB-R7: 文書情報 / 章ファイル情報の後余白（約3行。line-height 1.9 × 3）。',
    '   直後が TOC でも同じ 3 行。独立ページ化（nyoze-break-after-page）時は 0。 */',
    '.nyoze-web-book-flow .nyoze-document-info,',
    '.nyoze-web-book-flow .nyoze-chapter-info { margin-block-end: 5.7em; }',
    '.nyoze-web-book-flow .nyoze-document-info.nyoze-break-after-page,',
    '.nyoze-web-book-flow .nyoze-chapter-info.nyoze-break-after-page { margin-block-end: 0; }',
    '/* WB-R9: 簡易表紙（title page）。Tategaki 書籍モードの frontmatter 独立ページに',
    '   揃えた normal / center の 2 レイアウト。section は 1 ページ相当の slot、内側の',
    '   .nyoze-document-info-group がレイアウト container 兼 書字方向 override の対象で、',
    '   その中に「タイトル群」「著者・訳者群」を別 group として持つ（空 group は出力されない）。',
    '   group の書字方向 override は group 自身にだけ効き、本文 / TOC / chrome は変えない。',
    '   chapterInfo にはこの variant を出さない（semantic serializer 側の契約）。 */',
    '.nyoze-web-book-flow .nyoze-document-info--title-page {',
    '  box-sizing: border-box;',
    '  margin: 0;',
    '}',
    '.nyoze-web-book-flow .nyoze-document-info-group {',
    '  box-sizing: border-box;',
    '  min-inline-size: 0;',
    '  min-block-size: 0;',
    '  max-inline-size: 100%;',
    '  max-block-size: 100%;',
    '}',
    '.nyoze-web-book-flow .nyoze-document-info--title-page[data-nyoze-title-page-writing-mode="vertical-rl"] .nyoze-document-info-group { writing-mode: vertical-rl; }',
    '.nyoze-web-book-flow .nyoze-document-info--title-page[data-nyoze-title-page-writing-mode="horizontal-tb"] .nyoze-document-info-group { writing-mode: horizontal-tb; }',
    '/* title / credit の各 group は page slot 内に収める。長いタイトルは通常の日本語改行に',
    '   加え overflow-wrap: anywhere で連続文字列も折り返す（overflow: hidden の切り捨ては',
    '   使わない）。 */',
    '.nyoze-web-book-flow .nyoze-document-info-title-group,',
    '.nyoze-web-book-flow .nyoze-document-info-credit-group {',
    '  box-sizing: border-box;',
    '  min-inline-size: 0;',
    '  min-block-size: 0;',
    '  max-inline-size: 100%;',
    '  max-block-size: 100%;',
    '  overflow-wrap: anywhere;',
    '}',
    '/* normal レイアウト（Tategaki 通常）: タイトル群は開始側（上付き）、著者・訳者群は',
    '   地付き（text-align: end。縦書きでは下、横書きでは終了側）。 */',
    '.nyoze-web-book-flow .nyoze-document-info-title-group { margin-block-end: 1em; }',
    '.nyoze-web-book-flow .nyoze-document-info-credit-group { text-align: end; }',
    '/* center レイアウト（Tategaki 中央）: 実効書字方向（group 自身の書字方向）で判定する。',
    '   実効 horizontal: 単一の中央グループ（flex column + 両軸 center + text-align center）。 */',
    'body.nyoze-web-book-root[data-wb-writing-mode="horizontal-tb"] .nyoze-web-book-flow .nyoze-document-info--title-page[data-nyoze-title-page-layout="center"][data-nyoze-title-page-writing-mode="inherit"] .nyoze-document-info-group,',
    '.nyoze-web-book-flow .nyoze-document-info--title-page[data-nyoze-title-page-layout="center"][data-nyoze-title-page-writing-mode="horizontal-tb"] .nyoze-document-info-group {',
    '  display: flex;',
    '  flex-direction: column;',
    '  justify-content: center;',
    '  align-items: center;',
    '}',
    '/* 実効 vertical: Tategaki と同じく flex-direction: row + justify-content: space-between',
    '   （主軸 = inline = 上→下: タイトル上付き / 著者・訳者下付き）+ 交差軸 center',
    '   （physical horizontal center）。 */',
    'body.nyoze-web-book-root[data-wb-writing-mode="vertical-rl"] .nyoze-web-book-flow .nyoze-document-info--title-page[data-nyoze-title-page-layout="center"][data-nyoze-title-page-writing-mode="inherit"] .nyoze-document-info-group,',
    '.nyoze-web-book-flow .nyoze-document-info--title-page[data-nyoze-title-page-layout="center"][data-nyoze-title-page-writing-mode="vertical-rl"] .nyoze-document-info-group {',
    '  display: flex;',
    '  flex-direction: row;',
    '  justify-content: space-between;',
    '  align-items: center;',
    '}',
    '/* center: title / credit の text-align も center。normal の start / end を上書きする。 */',
    '.nyoze-web-book-flow .nyoze-document-info--title-page[data-nyoze-title-page-layout="center"] .nyoze-document-info-title-group,',
    '.nyoze-web-book-flow .nyoze-document-info--title-page[data-nyoze-title-page-layout="center"] .nyoze-document-info-credit-group {',
    '  text-align: center;',
    '  margin-block-end: 0;',
    '}',
    '/* center: 長いタイトルで credit 群が flex-shrink に潰されて page 外へあふれないよう、',
    '   縮むのはタイトル群側にする（縦書きではタイトルの inline-size 縮小が自然な再折返しになる）。 */',
    '.nyoze-web-book-flow .nyoze-document-info--title-page[data-nyoze-title-page-layout="center"] .nyoze-document-info-credit-group {',
    '  flex-shrink: 0;',
    '}',
    '.nyoze-web-book-flow .nyoze-document-info--title-page[data-nyoze-title-page-layout="center"] .nyoze-document-title,',
    '.nyoze-web-book-flow .nyoze-document-info--title-page[data-nyoze-title-page-layout="center"] .nyoze-document-credit {',
    '  text-align: center;',
    '}',
    '/* center: タイトルのみ / credit のみの場合は、単独 group を自然に中央へ',
    '   （space-between の主軸開始寄せを auto margin が吸収する）。 */',
    '.nyoze-web-book-flow .nyoze-document-info--title-page[data-nyoze-title-page-layout="center"] .nyoze-document-info-group > div:only-child {',
    '  margin: auto;',
    '}',
    '/* 表紙タイトル typography: Tategaki と同じ 2em 基準 + bold。ただし本文 h1（2em）より',
    '   明確に大きくするため 2.4em。色は theme の見出し色ではなく必ず本文色（--wb-fg）。',
    '   本文見出しの alignment / divider / margin-after は .nyoze-document-title 除外で',
    '   引き続き漏れない。 */',
    '.nyoze-web-book-flow .nyoze-document-info--title-page .nyoze-document-title {',
    '  font-size: 2.4em;',
    '  font-weight: bold;',
    '  margin: 0;',
    '  color: var(--wb-fg);',
    '}',
    '.nyoze-web-book-flow .nyoze-document-info--title-page .nyoze-document-credit {',
    '  color: var(--wb-fg);',
    '}',
    '/* 表紙 title / credit は Reader の見出し書体切替（見出し書体意味論）へ追従する。 */',
    'body.nyoze-web-book-root[data-wb-heading-font="mincho"] .nyoze-web-book-flow .nyoze-document-info--title-page .nyoze-document-info-group { font-family: var(--wb-font-family-mincho); }',
    'body.nyoze-web-book-root[data-wb-heading-font="gothic"] .nyoze-web-book-flow .nyoze-document-info--title-page .nyoze-document-info-group { font-family: var(--wb-font-family-gothic); }',
    'body.nyoze-web-book-root[data-wb-heading-font="same-as-body"] .nyoze-web-book-flow .nyoze-document-info--title-page .nyoze-document-info-group { font-family: var(--wb-font-family); }',
    '/* WB-R7 / WB-R8: 目次は通し番号なし + H1〜H6 の階層字下げ（flat list + level class）。',
    '   nested ol は作らない。論理 padding-inline-start のみ。',
    '   「目次」見出しは専用 class `.nyoze-toc-title` で固定見た目（本文見出し appearance 非適用）。',
    '   2文字分字下げ + 直後に約1行分の空行（margin-block-end: 1.9em）。 */',
    '.nyoze-web-book-flow .nyoze-toc-title {',
    '  margin: 0;',
    '  margin-block-end: 1.9em;',
    '  padding-inline-start: 2em;',
    '  font-size: 1.17em;',
    '  line-height: 1.9;',
    '  font-weight: bold;',
    '  font-family: inherit;',
    '  color: var(--wb-heading);',
    '  text-align: start;',
    '  border-block-end: none;',
    '}',
    '.nyoze-web-book-flow .nyoze-toc ol {',
    '  margin: 0;',
    '  padding-inline-start: 1em;',
    '  list-style: none;',
    '}',
    '.nyoze-web-book-flow .nyoze-toc-level-1 { padding-inline-start: 0; }',
    '.nyoze-web-book-flow .nyoze-toc-level-2 { padding-inline-start: 1em; }',
    '.nyoze-web-book-flow .nyoze-toc-level-3 { padding-inline-start: 2em; }',
    '.nyoze-web-book-flow .nyoze-toc-level-4 { padding-inline-start: 3em; }',
    '.nyoze-web-book-flow .nyoze-toc-level-5 { padding-inline-start: 4em; }',
    '.nyoze-web-book-flow .nyoze-toc-level-6 { padding-inline-start: 5em; }',
    '.nyoze-tcy { text-combine-upright: all; -webkit-text-combine: horizontal; }',
    /* WB-R12: auto TCY は縦書きのときだけ combine。横書き・横書き print では無効。 */
    'body[data-wb-writing-mode="vertical-rl"] .nyoze-web-book-auto-tcy {',
    '  text-combine-upright: all;',
    '  -webkit-text-combine: horizontal;',
    '}',
    '@media screen {',
    '  html, body { height: 100%; }',
    '  body.nyoze-web-book-root {',
    '    height: 100vh;',
    '    height: 100dvh;',
    '    max-height: 100vh;',
    '    max-height: 100dvh;',
    '    overflow: hidden;',
    '    display: flex;',
    '    flex-direction: column;',
    '    transition: opacity 0.2s ease;',
    '  }',
    '  .nyoze-web-book-main {',
    '    flex: 1 1 auto;',
    '    min-height: 0;',
    '    min-width: 0;',
    '    display: flex;',
    '    flex-direction: column;',
    '  }',
    '  .nyoze-web-book-paper-frame {',
    '    flex: 1 1 auto;',
    '    min-width: 0;',
    '    min-height: 0;',
    '    display: flex;',
    '    flex-direction: column;',
    '    position: relative;',
    '    overflow: hidden;',
    '  }',
    '  /* 用紙枠 ON: 紙面の外側に画面の地色を見せる（左右余白は16px以上を保つ）。 */',
    '  body.nyoze-web-book-root[data-wb-paper-frame="on"] {',
    '    background: var(--wb-canvas);',
    '  }',
    '  body.nyoze-web-book-root[data-wb-paper-frame="on"] .nyoze-web-book-paper-frame {',
    '    margin: 16px 24px 20px;',
    '    background: var(--wb-bg);',
    '    border: 1px solid var(--wb-chrome-border);',
    '    border-radius: 3px;',
    '    box-shadow: 0 4px 18px color-mix(in srgb, var(--wb-outline-shadow) 38%, transparent);',
    '  }',
    '  body.nyoze-web-book-root[data-wb-paper-frame="off"] .nyoze-web-book-paper-frame {',
    '    margin: 0;',
    '    border: 0;',
    '    border-radius: 0;',
    '    box-shadow: none;',
    '  }',
    '  .nyoze-web-book-viewport {',
    '    flex: 1 1 auto;',
    '    min-height: 0;',
    '    min-width: 0;',
    '    position: relative;',
    '    overflow: hidden;',
    '    outline: none;',
    '    background: var(--wb-bg);',
    '    color: var(--wb-fg);',
    '    /* WB-R13: let the browser keep vertical pan / pinch zoom native; only',
    '       horizontal gesture handling is ours (reader script calls',
    '       preventDefault() on a committed horizontal swipe, not globally).',
    '       pan-y alone drops pinch-zoom — pinch-zoom must be listed explicitly. */',
    '    touch-action: pan-y pinch-zoom;',
    '  }',
    '  /* screen reader furniture は physical inset 内だけに置く absolute overlay。',
    '     表示状態や内容を変えても viewport / pagination geometry を変えない。 */',
    '  .nyoze-web-book-reader-header,',
    '  .nyoze-web-book-reader-footer {',
    '    display: none;',
    '    box-sizing: border-box;',
    '    position: absolute;',
    '    z-index: 2;',
    '    left: 0;',
    '    right: 0;',
    '    width: 100%;',
    '    pointer-events: none;',
    '    writing-mode: horizontal-tb;',
    '    direction: ltr;',
    `    font-family: ${CHROME_FONT_FAMILY};`,
    '    font-size: 11px;',
    '    line-height: 14px;',
    '    color: var(--wb-muted);',
    '  }',
    '  body.nyoze-web-book-root[data-wb-header-enabled="on"] .nyoze-web-book-reader-header {',
    '    display: flex;',
    '    top: 1px;',
    '    padding: 0 16px;',
    '  }',
    '  body.nyoze-web-book-root[data-wb-footer-enabled="on"] .nyoze-web-book-reader-footer {',
    '    display: flex;',
    '    bottom: 1px;',
    '    padding: 0 16px;',
    '    font-variant-numeric: tabular-nums;',
    '  }',
    '  body.nyoze-web-book-root[data-wb-header-align="left"] .nyoze-web-book-reader-header,',
    '  body.nyoze-web-book-root[data-wb-footer-align="left"] .nyoze-web-book-reader-footer { justify-content: flex-start; }',
    '  body.nyoze-web-book-root[data-wb-header-align="center"] .nyoze-web-book-reader-header,',
    '  body.nyoze-web-book-root[data-wb-footer-align="center"] .nyoze-web-book-reader-footer { justify-content: center; }',
    '  body.nyoze-web-book-root[data-wb-header-align="right"] .nyoze-web-book-reader-header,',
    '  body.nyoze-web-book-root[data-wb-footer-align="right"] .nyoze-web-book-reader-footer { justify-content: flex-end; }',
    '  .nyoze-web-book-reader-header__content {',
    '    max-width: 100%;',
    '    overflow: hidden;',
    '    text-overflow: ellipsis;',
    '    white-space: nowrap;',
    '  }',
    '  .nyoze-web-book-reader-header__title,',
    '  .nyoze-web-book-reader-header__author,',
    '  .nyoze-web-book-reader-header__separator { display: none; }',
    '  body.nyoze-web-book-root[data-wb-header-show-title="on"] .nyoze-web-book-reader-header__title,',
    '  body.nyoze-web-book-root[data-wb-header-show-author="on"] .nyoze-web-book-reader-header__author { display: inline; }',
    '  body.nyoze-web-book-root[data-wb-header-show-title="on"][data-wb-header-show-author="on"] .nyoze-web-book-reader-header[data-wb-has-title="true"][data-wb-has-author="true"] .nyoze-web-book-reader-header__separator { display: inline; margin: 0 0.45em; }',
    '  .nyoze-web-book-flow {',
    '    column-fill: auto;',
    '    column-gap: var(--wb-column-gap);',
    '    column-width: var(--wb-column-width);',
    '    width: var(--wb-frame-width);',
    '    height: var(--wb-frame-height);',
    '    max-width: var(--wb-frame-width);',
    '    max-height: var(--wb-frame-height);',
    '  }',
    '  body.nyoze-web-book-root[data-wb-writing-mode="vertical-rl"] .nyoze-web-book-flow {',
    '    padding-top: var(--wb-effective-page-inset-top);',
    '    padding-bottom: var(--wb-effective-page-inset-bottom);',
    '    padding-left: var(--wb-effective-page-inset-inline);',
    '    padding-right: var(--wb-effective-page-inset-inline);',
    '    transform: translateY(var(--wb-page-offset));',
    '    text-align: justify;',
    '    text-align-last: auto;',
    '    text-justify: inter-character;',
    '  }',
    '  body.nyoze-web-book-root[data-wb-writing-mode="horizontal-tb"] .nyoze-web-book-flow {',
    '    padding-top: var(--wb-effective-page-inset-top);',
    '    padding-bottom: var(--wb-effective-page-inset-bottom);',
    '    padding-left: var(--wb-effective-page-inset-inline);',
    '    padding-right: var(--wb-effective-page-inset-inline);',
    '    transform: translateX(var(--wb-page-offset));',
    '  }',
    '  /* WB-R11: screen の画像は logical axis へ読み替えず、既存 frame と実効 physical inset から',
    '     導く本文矩形へ内接させる。intrinsic size を基準に auto のまま縮小だけを許可するため、',
    '     小さい画像を拡大せず、縦横比も歪めない。 */',
    '  .nyoze-web-book-flow img {',
    '    width: auto;',
    '    height: auto;',
    '    max-width: calc(var(--wb-frame-width) - var(--wb-effective-page-inset-inline) - var(--wb-effective-page-inset-inline));',
    '    max-height: calc(var(--wb-frame-height) - var(--wb-effective-page-inset-top) - var(--wb-effective-page-inset-bottom));',
    '    object-fit: contain;',
    '  }',
    '  /* 画像だけの段落は一つの column（logical page）に残す。inline image は paragraph の',
    '     意味論と inline layout を維持し、この selector の対象にしない。 */',
    '  .nyoze-web-book-flow p:has(> img:only-child) {',
    '    break-inside: avoid-column;',
    '  }',
    '  .nyoze-web-book-flow p:has(> img:only-child)::after {',
    '    content: none;',
    '  }',
    '  .nyoze-break-before-page { break-before: column; }',
    '  /* WB-R7: TOC 直後・文書情報独立ページは次の reader column へ。 */',
    '  .nyoze-web-book-flow .nyoze-toc,',
    '  .nyoze-web-book-flow .nyoze-break-after-page { break-after: column; }',
    '  /* WB-R9: title page は blank-page slot と同じく 1 column = 1 logical page を',
    '     ちょうど満たす（sizing は screen 専用 custom property だけを読む）。',
    '     layout container の group は slot を物理サイズで満たし、直交 flow でも',
    '     auto inline-size に依存しない。 */',
    '  body.nyoze-web-book-root[data-wb-writing-mode="vertical-rl"] .nyoze-web-book-flow .nyoze-document-info--title-page {',
    '    height: var(--wb-column-width);',
    '    width: 100%;',
    '  }',
    '  body.nyoze-web-book-root[data-wb-writing-mode="horizontal-tb"] .nyoze-web-book-flow .nyoze-document-info--title-page {',
    '    width: var(--wb-column-width);',
    '    height: 100%;',
    '  }',
    '  .nyoze-web-book-flow .nyoze-document-info--title-page .nyoze-document-info-group {',
    '    width: 100%;',
    '    height: 100%;',
    '  }',
    '  .nyoze-web-book-flow .nyoze-blank-page[data-nyoze-web-book-blank-page] {',
    '    break-before: column;',
    '    break-after: column;',
    '    box-sizing: border-box;',
    '    margin: 0;',
    '  }',
    '  body.nyoze-web-book-root[data-wb-writing-mode="vertical-rl"] .nyoze-web-book-flow .nyoze-blank-page[data-nyoze-web-book-blank-page] {',
    '    height: var(--wb-column-width);',
    '    width: 100%;',
    '  }',
    '  body.nyoze-web-book-root[data-wb-writing-mode="horizontal-tb"] .nyoze-web-book-flow .nyoze-blank-page[data-nyoze-web-book-blank-page] {',
    '    width: var(--wb-column-width);',
    '    height: 100%;',
    '  }',
    '',
    '  /* ============================================================',
    '     WB-R5 page transition — ornament only. Never changes pageIndex,',
    '     cached metrics, or the canonical flow transform. Duration is',
    '     snapshotted per run into inline --wb-transition-duration, so a',
    '     speed change never restarts a running animation.',
    '     ============================================================ */',
    '  .nyoze-web-book-transition-mask,',
    '  .nyoze-web-book-transition-overlay {',
    '    position: absolute;',
    '    inset: 0;',
    '    z-index: 1;',
    '    pointer-events: none;',
    '    opacity: 0;',
    '    writing-mode: horizontal-tb;',
    '    direction: ltr;',
    '  }',
    '  /* opaque paper-color mask: covers the whole reading viewport. */',
    '  .nyoze-web-book-transition-mask { background: var(--wb-bg); }',
    '  @keyframes wb-transition-fade-out {',
    '    from { opacity: 1; }',
    '    to { opacity: 0; }',
    '  }',
    '  @keyframes wb-transition-fade-in {',
    '    from { opacity: 0; }',
    '    to { opacity: 1; }',
    '  }',
    '  @keyframes wb-transition-zoom {',
    '    from { opacity: 0.35; transform: scale(0.985); }',
    '    to { opacity: 1; transform: scale(1); }',
    '  }',
    '  @keyframes wb-transition-slide-layer {',
    '    from { transform: translateX(0%); }',
    '    to { transform: translateX(var(--wb-transition-slide-exit-x, 0%)); }',
    '  }',
    '  /* forwards は fade-out 完了後の opacity 0 handoff（ちらつき防止）用。',
    '     class の除去は script の fade-in 開始 / cancel / cleanup 側の責務。 */',
    '  .nyoze-web-book-viewport.is-wb-transition-fade-out {',
    '    animation: wb-transition-fade-out var(--wb-transition-duration, 225ms) ease-in forwards;',
    '  }',
    '  .nyoze-web-book-viewport.is-wb-transition-fade-in {',
    '    animation: wb-transition-fade-in var(--wb-transition-duration, 275ms) ease-out;',
    '  }',
    '  .nyoze-web-book-viewport.is-wb-transition-zoom {',
    '    transform-origin: 50% 50%;',
    '    animation: wb-transition-zoom var(--wb-transition-duration, 500ms) ease-out;',
    '  }',
    '  .nyoze-web-book-transition-mask.is-wb-transition-slide {',
    '    opacity: 1;',
    '    animation: wb-transition-slide-layer var(--wb-transition-duration, 500ms) ease-out forwards;',
    '  }',
    '  .nyoze-web-book-transition-overlay.is-wb-transition-slide {',
    '    opacity: 1;',
    '    background: linear-gradient(to right, transparent, color-mix(in srgb, var(--wb-fg) 16%, transparent) 45%, transparent 85%);',
    '    animation: wb-transition-slide-layer var(--wb-transition-duration, 500ms) ease-out forwards;',
    '  }',
    '  /* slide 方向表（物理 x 軸のみ）:',
    '     | 書字方向 | next | previous |',
    '     | vertical-rl | 左 → 右 | 右 → 左 |',
    '     | horizontal-tb | 右 → 左 | 左 → 右 | */',
    '  body.nyoze-web-book-root[data-wb-writing-mode="vertical-rl"] .is-wb-transition-slide[data-wb-transition-direction="next"] {',
    '    --wb-transition-slide-exit-x: 100%;',
    '  }',
    '  body.nyoze-web-book-root[data-wb-writing-mode="vertical-rl"] .is-wb-transition-slide[data-wb-transition-direction="previous"] {',
    '    --wb-transition-slide-exit-x: -100%;',
    '  }',
    '  body.nyoze-web-book-root[data-wb-writing-mode="horizontal-tb"] .is-wb-transition-slide[data-wb-transition-direction="next"] {',
    '    --wb-transition-slide-exit-x: -100%;',
    '  }',
    '  body.nyoze-web-book-root[data-wb-writing-mode="horizontal-tb"] .is-wb-transition-slide[data-wb-transition-direction="previous"] {',
    '    --wb-transition-slide-exit-x: 100%;',
    '  }',
    '}',
    '',
    '@media print {',
    '  @page { margin: 15mm; }',
    '  html, body { height: auto; }',
    '  body.nyoze-web-book-root {',
    '    display: block;',
    '    min-height: 0;',
    '    height: auto !important;',
    '    max-height: none !important;',
    '    overflow: visible !important;',
    '    background: #ffffff !important;',
    '    color: #1a1a1a !important;',
    '    --wb-bg: #ffffff !important;',
    '    --wb-fg: #1a1a1a !important;',
    '    --wb-heading: #1a1a1a !important;',
    '    --wb-muted: #444444 !important;',
    '    --wb-canvas: #ffffff !important;',
    '    --wb-chrome-bg: #ffffff !important;',
    '    --wb-chrome-border: #1a1a1a !important;',
    '    --wb-chrome-fg: #1a1a1a !important;',
    '    --wb-outline-bg: #ffffff !important;',
    '    --wb-accent: #1a1a1a !important;',
    '  }',
    '  .nyoze-web-book-flow h1, .nyoze-web-book-flow h2, .nyoze-web-book-flow h3,',
    '  .nyoze-web-book-flow h4, .nyoze-web-book-flow h5, .nyoze-web-book-flow h6 {',
    '    color: #1a1a1a !important;',
    '  }',
    '  body.nyoze-web-book-root[data-wb-writing-mode="vertical-rl"] { writing-mode: vertical-rl; direction: ltr; }',
    '  body.nyoze-web-book-root[data-wb-writing-mode="horizontal-tb"] { writing-mode: horizontal-tb; direction: ltr; }',
    '  .nyoze-web-book-chrome,',
    '  .nyoze-web-book-settings,',
    '  .nyoze-web-book-backdrop,',
    '  .nyoze-web-book-outline,',
    '  .nyoze-web-book-reader-header,',
    '  .nyoze-web-book-reader-footer,',
    '  .nyoze-web-book-transition-mask,',
    '  .nyoze-web-book-transition-overlay,',
    '  #nyoze-web-book-chapter-titles {',
    '    display: none !important;',
    '  }',
    '  /* WB-R5: print の実効遷移は常に none（script が print 開始時に cleanup',
    '     する。ここは印刷 rasterize 中の CSS 側の安全網）。 */',
    '  .nyoze-web-book-viewport {',
    '    animation: none !important;',
    '  }',
    '  .nyoze-web-book-main {',
    '    display: block;',
    '    min-height: 0;',
    '  }',
    '  .nyoze-web-book-paper-frame {',
    '    display: block;',
    '    margin: 0 !important;',
    '    border: 0 !important;',
    '    box-shadow: none !important;',
    '    background: transparent !important;',
    '  }',
    '  .nyoze-web-book-viewport {',
    '    overflow: visible !important;',
    '    height: auto !important;',
    '    width: auto !important;',
    '    background: #ffffff !important;',
    '    color: #1a1a1a !important;',
    '  }',
    '  .nyoze-web-book-flow {',
    '    columns: unset !important;',
    '    column-width: auto !important;',
    '    column-gap: normal !important;',
    '    column-fill: auto !important;',
    '    height: auto !important;',
    '    width: auto !important;',
    '    max-height: none !important;',
    '    max-width: none !important;',
    '    padding: 0 !important;',
    '    transform: none !important;',
    '    color: #1a1a1a !important;',
    '  }',
    '  /* print は黒系本文に固定するため、link も accent を持ち込まない。 */',
    '  .nyoze-web-book-flow a { color: inherit !important; }',
    '  /* WB-R11: print は screen の frame-height を引き継がない。横幅だけを用紙本文幅に',
    '     収め、intrinsic aspect ratio は維持する。厳密な印刷画像組版は別スライス。 */',
    '  .nyoze-web-book-flow img {',
    '    width: auto !important;',
    '    height: auto !important;',
    '    max-width: 100% !important;',
    '    max-height: none !important;',
    '    object-fit: contain;',
    '  }',
    '  .nyoze-web-book-root[data-wb-writing-mode="vertical-rl"] .nyoze-web-book-flow { inline-size: 235mm !important; block-size: auto !important; }',
    '  /* WB-R3: print でも縦書きの通常本文 / 通常 list は justify。見出し・directive・TOC・',
    '     metadata・code・task row は上の常設 text-align ルールが継承を遮断する。 */',
    '  body.nyoze-web-book-root[data-wb-writing-mode="vertical-rl"] .nyoze-web-book-flow {',
    '    text-align: justify;',
    '    text-align-last: auto;',
    '    text-justify: inter-character;',
    '  }',
    '  .nyoze-break-before-page {',
    '    break-before: page;',
    '    page-break-before: always;',
    '  }',
    '  /* WB-R7: print では TOC 後・文書情報後から次の印刷ページ。 */',
    '  .nyoze-web-book-flow .nyoze-toc,',
    '  .nyoze-web-book-flow .nyoze-break-after-page {',
    '    break-after: page;',
    '    page-break-after: always;',
    '  }',
    '  /* WB-R9: print の title page。screen pagination state は流用せず、縦書きは flow の',
    '     有限 inline size (235mm) 全長を group が満たして layout を成立させ、横書きは',
    '     1 ページに収まる保守的な min-height を group に与える best effort（末尾空白',
    '     ページを作らないことを優先）。 */',
    '  body.nyoze-web-book-root[data-wb-writing-mode="vertical-rl"] .nyoze-web-book-flow .nyoze-document-info--title-page {',
    '    inline-size: 100%;',
    '  }',
    '  body.nyoze-web-book-root[data-wb-writing-mode="vertical-rl"] .nyoze-web-book-flow .nyoze-document-info--title-page .nyoze-document-info-group {',
    '    height: 100%;',
    '  }',
    '  body.nyoze-web-book-root[data-wb-writing-mode="horizontal-tb"] .nyoze-web-book-flow .nyoze-document-info--title-page .nyoze-document-info-group {',
    '    min-height: calc(100vh - 45mm);',
    '  }',
    '  .nyoze-web-book-flow .nyoze-blank-page[data-nyoze-web-book-blank-page] {',
    '    break-before: page;',
    '    break-after: page;',
    '    page-break-before: always;',
    '    page-break-after: always;',
    '    height: auto !important;',
    '    width: auto !important;',
    '    min-height: 0;',
    '  }',
    '}',
  ].join('\n')
}
